### PR TITLE
fix: fix font change issue

### LINKED ISSUE #4: Using the addon changes the fonts of the application
It seems that adding this addon introduces a change in font size in the application as shown in the following image:

image

### PR DESCRIPTION
**Pull request by paodb**
Close #4

### CODE REVIEW

File: src/main/java/com/flowingcode/vaadin/addons/chipfield/ChipField.java [hunk 1]
```diff
@@ -19,6 +19,14 @@
  */
 package com.flowingcode.vaadin.addons.chipfield;
 
+import java.util.ArrayList;
```
Comment (javier-godoy) [inline src/main/java/com/flowingcode/vaadin/addons/chipfield/ChipField.java:22]: Use the code formatter

**Review by javier-godoy — CHANGES_REQUESTED** [review]

File: src/main/java/com/flowingcode/vaadin/addons/chipfield/ChipField.java (hunk 1 above)
Comment (paodb) [reply src/main/java/com/flowingcode/vaadin/addons/chipfield/ChipField.java]: Done.

**Review by javier-godoy — APPROVED** [review]
